meta_product_name: "Fit It"
meta_title: "Fit It - Clean layout Clear mind"
meta_description: "Visualize a better layout and decide the location of furniture for your new home"
meta_image: "LandingPageBg.svg" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"
